name: interactive_viewer_plus
description: "Improvements on default Flutter InteractiveViewer widget"
version: 0.0.2
homepage: https://github.com/burhankhanzada/interactive_viewer_plus

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint_hard: ^6.2.1
